config/routes.rb
Rails.application.routes.draw do
  resources :main_menus
  root to: "main_menus#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/main_menu.rb
class MainMenu < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_menus_controller.rb
class MainMenusController < ApplicationController
  before_action :set_main_menu, only: %i[ show edit update destroy ]

  # GET /main_menus or /main_menus.json
  def index
    @main_menus = MainMenu.all
  end

  # GET /main_menus/1 or /main_menus/1.json
  def show
  end

  # GET /main_menus/new
  def new
    @main_menu = MainMenu.new
  end

  # GET /main_menus/1/edit
  def edit
  end

  # POST /main_menus or /main_menus.json
  def create
    @main_menu = MainMenu.new(main_menu_params)

    respond_to do |format|
      if @main_menu.save
        format.html { redirect_to @main_menu, notice: "Main menu was successfully created." }
        format.json { render :show, status: :created, location: @main_menu }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @main_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /main_menus/1 or /main_menus/1.json
  def update
    respond_to do |format|
      if @main_menu.update(main_menu_params)
        format.html { redirect_to @main_menu, notice: "Main menu was successfully updated." }
        format.json { render :show, status: :ok, location: @main_menu }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @main_menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /main_menus/1 or /main_menus/1.json
  def destroy
    @main_menu.destroy
    respond_to do |format|
      format.html { redirect_to main_menus_url, notice: "Main menu was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_main_menu
      @main_menu = MainMenu.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def main_menu_params
      params.fetch(:main_menu, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_menus_helper.rb
module MainMenusHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Story</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main_menus/_form.html.erb
<%= form_with(model: main_menu) do |form| %>
  <% if main_menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(main_menu.errors.count, "error") %> prohibited this main_menu from being saved:</h2>

      <ul>
        <% main_menu.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ui segment">
    <% form_with model: @main_menu do |form| %>
      <div>
        <h3>hi</h3>
        <%= form.text_field :name %>      
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/main_menus/edit.html.erb
<h1>Editing Main Menu</h1>

<%= render 'form', main_menu: @main_menu %>

<%= link_to 'Show', @main_menu %> |
<%= link_to 'Back', main_menus_path %>

app/views/main_menus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Main Page</h1>

<table class="ui table">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @main_menus.each do |main_menu| %>
      <tr>
        <td><%= link_to main_menu.id, main_menu %></td>
        <td><%= link_to 'Edit', edit_main_menu_path(main_menu) %></td>
        <td><%= link_to 'Destroy', main_menu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Main Menu', new_main_menu_path %>

app/views/main_menus/new.html.erb
<h1>New Main Menu</h1>

<%= render 'form', main_menu: @main_menu %>

<%= link_to 'Back', main_menus_path %>

app/views/main_menus/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_main_menu_path(@main_menu) %> |
<%= link_to 'Back', main_menus_path %>